- impl/src/main/java/org/jboss/forge/roaster/model/impl/MethodImpl.java
- impl/src/test/java/org/jboss/forge/test/roaster/model/MethodSignatureTest.java
avoid qualified names using "$".
Note: there may be other places where this problem happens
> Qualify inner classes correctly

- impl/src/main/java/org/jboss/forge/roaster/model/util/Formatter.java
- impl/src/test/java/org/jboss/forge/test/roaster/model/JavaDocTest.java
- impl/src/test/java/org/jboss/forge/test/roaster/model/util/FormatterTest.java
https://issues.jboss.org/browse/ROASTER-54
> ROASTER-54: Formatter isn't apply on Javadoc

- api/src/main/java/org/jboss/forge/roaster/model/source/AnnotationTargetSource.java
- api/src/main/java/org/jboss/forge/roaster/model/util/Methods.java
- impl/src/main/java/org/jboss/forge/roaster/model/ast/AnnotationAccessor.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AnnotationElementImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/EnumConstantBodyImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/EnumConstantImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/FieldImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaPackageInfoImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/MethodImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/ParameterImpl.java
- impl/src/test/java/org/jboss/forge/test/roaster/model/MethodImplementationTest.java
- impl/src/test/java/org/jboss/forge/test/roaster/model/common/MockAnnotatedInterface.java
I add removeAnnotations method on all annotations holder.
Then a call this method on methodSource and all parameter of implemented
methods.
If you implements an iterface, you'll get all inherited methods without annotaitons.
> ROASTER-92 : implementInterface shouldn't copy annotation

- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaPackageInfoImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/TypeImpl.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:HiddenFieldCheck Local variables should not shadow class fields.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AHiddenFieldCheck
George Kankava
> Local variables should not shadow class fields

- api/src/main/java/org/jboss/forge/roaster/model/util/DesignPatterns.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/FieldImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaEnumImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaPackageInfoImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/MethodImpl.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:UselessParenthesesCheck Useless parentheses around expressions should be removed to prevent any misunderstanding.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AUselessParenthesesCheck
George Kankava
> Useless parentheses around expressions should be removed to prevent any misunderstanding

- api/src/main/java/org/jboss/forge/roaster/model/util/Strings.java
This pull request is focused on resolving occurrence of Sonar rule
squid:S1197 Array designators "[]" should be on the type, not the variable.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1197
George Kankava
> squid:S1197 Array designators "[]" should be on the type, not the variable

- api/src/main/java/org/jboss/forge/roaster/model/util/Assert.java
- api/src/main/java/org/jboss/forge/roaster/model/util/DesignPatterns.java
- api/src/main/java/org/jboss/forge/roaster/model/util/Methods.java
- api/src/main/java/org/jboss/forge/roaster/model/util/Refactory.java
- api/src/main/java/org/jboss/forge/roaster/model/util/Types.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - Utility classes should not have public constructors.
https://dev.eclipse.org/sonar/rules/show/squid:S1118
George Kankava
> squid:S1118 - Utility classes should not have public constructors

- api/src/main/java/org/jboss/forge/roaster/Roaster.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1118 - Utility classes should not have public constructors.
squid:S1155 - Collection.isEmpty() should be used to test for emptiness.
squid:S1488 - Local Variables should not be declared and then immediately returned or thrown.
https://dev.eclipse.org/sonar/rules/show/squid:S1118
https://dev.eclipse.org/sonar/rules/show/squid:S1155
https://dev.eclipse.org/sonar/rules/show/squid:S1488
George Kankava
> multiple code improvements: squid:S1118, squid:S1155, squid:S1488

- dist/src/main/java/org/jboss/forge/roaster/Bootstrap.java
- impl/src/main/java/org/jboss/forge/roaster/model/ast/AnnotationAccessor.java
- impl/src/main/java/org/jboss/forge/roaster/model/ast/ModifierAccessor.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1118 Utility classes should not have public constructors.
squid:S2325 private methods that don't access instance data should be static.
squid:S1066 Collapsible "if" statements should be merged.
squid:S1155 Collection.isEmpty() should be used to test for emptiness.
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1118
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS2325
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1066
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AS1155
George Kankava
> multiple code improvements: squid:S1066, squid:S1155, squid:S1118, squid:S2325

- api/src/main/java/org/jboss/forge/roaster/model/util/Types.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/MethodReturnTypeTest.java
The tokens for generics were incomplete when using them as a return type. This has been fixed.
However, I had to modify the test case so it makes the same assumption as `testReturnTypeShouldKeepGenerics` and `testGetReturnTypeReturnsFullTypeForJavaLangGeneric`. Right now, the generics are not returned qualified despite the fact that this is mentioned in the documentation:
> Returns the type's qualified name, preserving type parameters (which are also qualified)
> ROASTER-110: Allow nested generic types for method return types

- dist/src/main/resources/bin/roaster
- dist/src/main/resources/bin/roaster.bat
The class path pointed to an non existing directory and could not find the `Boostrap` class. 
_problem_
When `./roaster` command was called, it gave error:
`Error: Could not find or load main class org.jboss.forge.roaster.Bootstrap`
_steps to reproduce_
* `git clone git@github.com:forge/roaster.git`
* `cd roaster`
* `mvn compile`
* `cd dist/target/classes/bin`
* `./roaster`
the error previously mentioned happens at this point.
> updated class path

- api/src/main/java/org/jboss/forge/roaster/model/source/Importer.java
- api/src/main/java/org/jboss/forge/roaster/model/util/Types.java
- api/src/test/java/org/jboss/forge/roaster/model/util/TypesTest.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaClassImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/JavaClassGenericsTest.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/common/JavaClassTestBase.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/common/WildCardImportsTest.java
Hi,
this pull request is to solve ROASTER-117.
I did the following:
* improve the splitGeneric method to with nested generics
* change the setSuperType method to use the splitGeneric  method
* change the requireImport method to check also the type parameters
* change the addImport method to also import the type parameters
Since this touching core components, please take a closer look to it. I want to avoid any regressions or unexpected behaviour. Currently all test are green, but maybe you find something.
Best regards,
Kai
> ROASTER-117: Allow nested generic types in setSuperType

- api/src/main/java/org/jboss/forge/roaster/model/source/Import.java
- api/src/main/java/org/jboss/forge/roaster/model/source/Importer.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/ImportImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/ImportTest.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/common/JavaClassTestBase.java
Hi,
I added the following:
* enhancement of the resolveType logic (performance)
* add a special case to resolveType where only one wildcard import is present
* some tests & javadoc
* I needed to fix some problems inside the ImportImpl since missing handling for wildcards preventing my change
Please review.
I add a issue to revisit the getQualifiedName logic in the import since it returns the package for wildcard imports which is not very nice.
Also I know that I added a TODO in one test for wildcard resolvers (so this TODO is there by purpose but I was not able to add a import resolver in a easy way).
Best regards,
Kai
> Roaster 23: Improve the resolve type logic and fix wildcard import problems

- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSourceMemberHolder.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaAnnotationImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaClassImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaEnumImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaPackageInfoImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaSourceImpl.java
Hi,
I've seen that JavaPackageInfoImpl contains a lot of duplicate code which can be avoided by creating a new abstract basis class for java sources. Both, JavaPackageInfoImpl and AbstractJavaSource now only containing only necessary methods while the base work is done JavaSourceImpl.
Because of such massive copy work the pr is quite big, while not changing any logic.
-- Kai
> Avoid duplicate code in JavaPackageInfoImpl

- api/src/test/java/org/jboss/forge/roaster/model/util/StringsTest.java
Hi,
I've analysed your codebase and have noticed some gaps in the coverage of the strings utility, `Strings.java`.
I've written a few tests for this class with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/datasheet). 
Hopefully these tests should help you detect regressions caused by future code changes. Please let me know if you'd be interested in having more tests written for other classes within this project, I would be happy to help.
Also, while writing the tests I noticed a strange behaviour of `Strings.stripQuotes` - the final character of a quoted string is removed along with the quotes (so `Strings.stripQuotes("\'sample\'") == "sampl"`). My tests currently verify this behaviour, but I'd be happy to fix the bug and change the tests instead if …
> Added tests for org.jboss.roaster.model.util.Strings.

- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaPackageInfoImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaSourceImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/util/Formatter.java
- impl/src/main/java/org/jboss/forge/roaster/model/util/JDTOptions.java
- impl/src/main/java/org/jboss/forge/roaster/spi/JavaParserImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/util/JDTOptionsTest.java
Hi,
before I start to work on some more issues, I took some time to remove some more duplicate code. This includes the stuff I did two days ago via PR. Also I found, that the parser options are hardcoded in some files. So I created a util class in which the options are globally available. That also fixed a bug, where in one file still Java 1.7 was used instead of Java 1.8
Please review.
-- Kai
> Remove more duplicate code

- api/src/main/java/org/jboss/forge/roaster/model/source/Import.java
- api/src/main/java/org/jboss/forge/roaster/model/source/Importer.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSourceMemberHolder.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/ImportImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaSourceImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/ImportTest.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/common/JavaClassTestBase.java
Hey,
I worked on an improvement on the import class (ImportImpl). It turned out more complicated and during the development I found other issues within the code.
In short words:
* getSimpleName now uses a more improved way
* getQualifiedName now returnes the full name instead of a package if a wildcard import is used
*  getImport now only works for fqn names (as the javadoc says) --> some changes needed therefore
* resolveType now checkes for simple name eq. in the imports
* validImport didn't worked for wildcard issues --> bug
BR,
Kai
> ROASTER-133: Improve the Import Impl.

- api/src/main/java/org/jboss/forge/roaster/model/source/MethodSource.java
- api/src/main/java/org/jboss/forge/roaster/model/util/Types.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaSourceImpl.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/MethodImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/util/TypesTest.java
Hi,
I found some more wrongly assumes imports in setReturnType & addThrows. To be able to implement this, I added two new helper function inside Types. I think _toResolvedType_ is a really helpful method and should be used in other areas where currently own logic is implemented.
In addition, I found some issues in
* isJavaLang
* addImport
* getImport
BR,
Kai
> Fix import logic in setReturnType & addThrows

- .github/workflows/maven.yml
- api/src/main/java/org/jboss/forge/roaster/model/util/Types.java
- tests/pom.xml
- tests/src/test/java/org/jboss/forge/test/roaster/model/util/TypesTest.java
This commit fixes the handling of types like List<? extends Number> in Types.toResolvedType.
> ROASTER-135: Fix wildcard handling in Types.toResolvedType

- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaDocTagImpl.java
When you have @param that span multiple lines, then the text is appended without a space separating them
```
In Camel we use this to generate some source code with javadoc parameters and notice that "forthis" vs "for this"
-    @UriParam(description = "The unique id of the Account that is responsible forthis resource")
+    @UriParam(description = "The unique id of the Account that is responsible for this resource")
* @param pathAddressSid The unique id of the Account that is responsible fort
*                     his resource
```
> Fix getting parameter value from JavaDocTag

- impl/src/main/java/org/jboss/forge/roaster/model/impl/ClassLoaderWildcardImportResolver.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/ClassLoaderWildcardImportResolverTest.java
- tests/src/test/resources/org/jboss/forge/grammar/java/MockWildcardClass.java
ClassLoaderWildcardImportResolver was looking for a.b.c.*.CLASSNAME instead of a.b.c.CLASSNAME
> Fixes #214 - ClassLoaderWildcardImportResolver fails to find type

- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaDocImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/JavaDocTest.java
> Handle spaces in JavadocImpl.getFullSpace

- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSourceMemberHolder.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/JavaInterfaceTest.java
> Simplified `AbstractJavaSourceMemberHolder#addInterface(java.lang.String)`

- api/src/main/java/org/jboss/forge/roaster/model/JavaRecord.java
- api/src/main/java/org/jboss/forge/roaster/model/source/JavaRecordSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractInterfaceCapableJavaSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSourceMemberHolder.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JDTHelper.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaRecordImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/JavaRecordTest.java
> Support interfaces in Records

- api/src/main/java/org/jboss/forge/roaster/model/source/AnnotationElementSource.java
- impl/src/main/java/org/jboss/forge/roaster/model/impl/AnnotationElementImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/JavaAnnotationTest.java
> Support Javadoc in AnnotationElement

- .github/workflows/codeql-analysis.yml
- .github/workflows/maven.yml
- dist/pom.xml
- impl/pom.xml
- pom.xml
Eclipse JDT minimum release is JDK 17
> Update to JDK 17

- impl/src/main/java/org/jboss/forge/roaster/model/impl/FieldImpl.java
- tests/src/test/java/org/jboss/forge/test/roaster/model/FieldMultipleTest.java
- Update test suite to include validation for multiple field declarations using AssertJ.
- Refactor `getName` method in `FieldImpl` for more efficient retrieval of fully qualified names.
- Fixes #339
> Fix multi-field name parsing
