forge/roaster

api/src/main/java/org/jboss/forge/roaster/model/util/SerialVersionUIDComputer.java, tests/src/test/java/org/jboss/forge/test/roaster/model/util/SerialVersionUIDComputerTest.java
I hope I did it well...
I'm still not common with PR :fearful:
=> ROASTER-103: Remove test on Serializable class implementation.

impl/src/main/java/org/jboss/forge/roaster/model/impl/TypeImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/MethodSignatureTest.java
=> add support for archaic form of array declarations:  char value[]

api/src/main/java/org/jboss/forge/roaster/model/util/Types.java, tests/src/test/java/org/jboss/forge/test/roaster/model/JavaDocTest.java
As discussed in [https://issues.jboss.org/browse/ROASTER-107](url)
=> Tweaking ROASTER-107 and correcting line separators for Windows compat

api/src/main/java/org/jboss/forge/roaster/model/util/Types.java, api/src/test/java/org/jboss/forge/roaster/model/util/TypesTest.java
- add the generics before the array declaration
- add unit tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/forge/roaster/66)
=> Support arrays in Types.toSimpleName().

api/src/main/java/org/jboss/forge/roaster/model/Abstractable.java, api/src/main/java/org/jboss/forge/roaster/model/AnnotationElement.java, api/src/main/java/org/jboss/forge/roaster/model/EnumConstant.java, api/src/main/java/org/jboss/forge/roaster/model/Extendable.java, api/src/main/java/org/jboss/forge/roaster/model/FieldHolder.java, api/src/main/java/org/jboss/forge/roaster/model/JavaAnnotation.java, api/src/main/java/org/jboss/forge/roaster/model/JavaClass.java, api/src/main/java/org/jboss/forge/roaster/model/JavaType.java, api/src/main/java/org/jboss/forge/roaster/model/MemberHolder.java, api/src/main/java/org/jboss/forge/roaster/model/MethodHolder.java, api/src/main/java/org/jboss/forge/roaster/model/Named.java, api/src/main/java/org/jboss/forge/roaster/model/Packaged.java, api/src/main/java/org/jboss/forge/roaster/model/PropertyHolder.java, api/src/main/java/org/jboss/forge/roaster/model/SyntaxError.java, api/src/main/java/org/jboss/forge/roaster/model/source/AbstractableSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/AnnotationElementSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/EnumConstantSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/ExtendableSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/FieldHolderSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/Importer.java, api/src/main/java/org/jboss/forge/roaster/model/source/JavaAnnotationSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/MemberHolderSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/NamedSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/PackagedSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/PropertyHolderSource.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSourceMemberHolder.java, tests/src/test/java/org/jboss/forge/test/roaster/model/JavaClassPropertyTest.java, tests/src/test/java/org/jboss/forge/test/roaster/model/JavaPackageInfoTest.java, tests/src/test/java/org/jboss/forge/test/roaster/model/common/MockNestingAnnotation.java
Adding PropertyHolderSource.getProperties(Class<?>) with test case, some cleanup.
=> Roaster 35

api/src/main/java/org/jboss/forge/roaster/model/util/Types.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/TypeImpl.java
I profiled my Roaster based code generator, and I found two suboptimal implementation.
I added fast return statements for most frequently used execution paths.
With these modifications my code generation time reduced from 147 sec to 21 sec.
(All junit tests successfully completed after the modifications)
=> Performance improvements

impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSourceMemberHolder.java, tests/src/test/java/org/jboss/forge/test/roaster/model/JavaInterfaceTest.java
https://issues.jboss.org/browse/ROASTER-127
=> ROASTER-127 Interface without package in the qualified name

impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java, tests/src/test/java/org/jboss/forge/test/roaster/model/common/AnnotationTest.java, tests/src/test/java/org/jboss/forge/test/roaster/model/common/JavaClassTestBase.java, tests/src/test/resources/org/jboss/forge/grammar/java/MockAnnotatedClass.java, tests/src/test/resources/org/jboss/forge/grammar/java/MockAnnotatedEnumConstant.java, tests/src/test/resources/org/jboss/forge/grammar/java/MockAnnotatedField.java, tests/src/test/resources/org/jboss/forge/grammar/java/MockAnnotatedMethod.java, tests/src/test/resources/org/jboss/forge/grammar/java/MockAnnotatedParameter.java
Co-authored-by: Kai Müller <15907922+kaijMueller@users.noreply.github.com>
=> ROASTER-128: Additional checks to prevent illegal imports

api/src/main/java/org/jboss/forge/roaster/model/source/Importer.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractJavaSource.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/FieldImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/FieldTypeTest.java, tests/src/test/java/org/jboss/forge/test/roaster/model/ImportTest.java
Fixes ROASTER-10
fix: addImport JavaDoc improved
Fixes ROASTER-129
=> fix: addImport should return null if the import cannot be resolved or imported

impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaClassImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/common/JavaClassTestBase.java
Hi,
with the help of [pull request 67](https://github.com/forge/roaster/pull/67) I found an additional issue in the import logic. This request contains the fix and the tests for it, which were provided in the [pull request 67](https://github.com/forge/roaster/pull/67).
Can somebody please check?
BR,
Kai
=> Fix an issue with the import of the super type

tests/src/test/java/org/jboss/forge/test/roaster/model/ParsingPerformanceTest.java
Hi,
I removed the @Ignore annotation from this test and improved the code a little bit.
Can somebody please check and merge?
BR,
Kai
=> ROASTER-106 remove the ignore annotation

.gitignore, api/src/main/java/org/jboss/forge/roaster/model/source/ExtendableSource.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaClassImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/common/JavaClassTestBase.java
Hi,
I found that the super type "remove" (type parameter is null) is not consistent across the methods. Therefore I improved it, added the necessary tests, fixed a new bug with the super type import handling and added the "bin folder" to the gitignore.
BR,
Kai
=> Adding an improved null handling for the super type

api/src/main/java/org/jboss/forge/roaster/Internal.java, api/src/main/java/org/jboss/forge/roaster/Origin.java, api/src/main/java/org/jboss/forge/roaster/ParserException.java, api/src/main/java/org/jboss/forge/roaster/Problem.java, api/src/main/java/org/jboss/forge/roaster/Roaster.java, api/src/main/java/org/jboss/forge/roaster/Streams.java
Hi,
I added a lot of javadoc comments to the sources in org.jboss.forge.roaster. In addition, I removed unused methods and improved the code quality if it was obvious (e.g. use try with resources).
Best regards,
Kai
=> Improved the code of package org.jboss.forge.roaster

dist/src/main/java/org/jboss/forge/roaster/Bootstrap.java, dist/src/main/java/org/jboss/forge/roaster/CommandRunner.java, dist/src/main/java/org/jboss/forge/roaster/FormatterCommand.java, dist/src/main/java/org/jboss/forge/roaster/HelpCommand.java
Hi,
I improved the distribution project by splitting the code across some classes, defining an interface and removing unnecessary code. In addition, I resolved some compiler warnings.
Kai
=> Improve Bootstrap

api/src/main/java/org/jboss/forge/roaster/model/Abstractable.java, api/src/main/java/org/jboss/forge/roaster/model/AnnotationElement.java, api/src/main/java/org/jboss/forge/roaster/model/EnumConstant.java, api/src/main/java/org/jboss/forge/roaster/model/JavaClass.java, api/src/main/java/org/jboss/forge/roaster/model/JavaType.java, api/src/main/java/org/jboss/forge/roaster/model/Member.java, api/src/main/java/org/jboss/forge/roaster/model/Method.java, api/src/main/java/org/jboss/forge/roaster/model/Property.java, api/src/main/java/org/jboss/forge/roaster/model/source/AbstractableSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/JavaClassSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/JavaEnumSource.java, api/src/main/java/org/jboss/forge/roaster/model/source/JavaInterfaceSource.java, api/src/main/java/org/jboss/forge/roaster/model/util/Methods.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/AbstractGenericCapableJavaSource.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/AnnotationElementImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/AnnotationImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/EnumConstantBodyImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/EnumConstantImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/FieldImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaDocImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaInterfaceImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaInterfaceMethodImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaPackageInfoImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/MethodImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/ParameterImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/PropertyImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/TypeImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/TypeVariableImpl.java
Hi,
I resolved various compiler warnings:
* Removed empty javadoc
* Removed duplicate type information
* Removed duplicate interfaces
* Removed not used imports
* Removed unused types in generics
* Removed not needed else clauses
Kai
=> Resolve various compiler warnings

api/src/main/java/org/jboss/forge/roaster/model/util/Assert.java, api/src/main/java/org/jboss/forge/roaster/model/util/Types.java, tests/src/test/java/org/jboss/forge/test/roaster/model/util/TypesTest.java
Hi,
I improved the types utility a little bit.
Kai
=> Improving types utility

api/src/main/java/org/jboss/forge/roaster/model/util/FormatterProfileReader.java, api/src/main/java/org/jboss/forge/roaster/model/util/Methods.java, api/src/main/java/org/jboss/forge/roaster/model/util/Refactory.java, api/src/main/java/org/jboss/forge/roaster/model/util/SerialVersionUIDComputer.java
Solving some minor compiler warnings, adding/impr. javadoc & some small code changes
=> Imroving the API utility

api/src/main/java/org/jboss/forge/roaster/model/Annotation.java, impl/src/main/java/org/jboss/forge/roaster/model/ast/AnnotationAccessor.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/AnnotationImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaSourceImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/Strings.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/TypeVariableImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/common/AnnotationTest.java, tests/src/test/java/org/jboss/forge/test/roaster/model/common/JavaClassTestBase.java
While working on some stuff in the annotations, I found some inelegant handling of annotation names. While changing this, I found some other stuff in regards of naming and importing of annotations.
This commit now includes some improvements but mostly fixes.
Btw, some files were not formatted, so while formatting my changes the eclipse formatter also changed the other code. So, this commit seems so big, because of this
BR,
Kai
=> Improving and fixing annotations

api/src/main/java/org/jboss/forge/roaster/model/util/Types.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/AnnotationImpl.java
Hi,
I did some refactor work at AnnotationImpl as a base work to analyse ROASTER-130
=> Refactor AnnotationImpl

.github/workflows/maven.yml, impl/src/main/java/org/jboss/forge/roaster/model/impl/MethodImpl.java, impl/src/main/java/org/jboss/forge/roaster/spi/JavaParserImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/MethodSignatureTest.java
=> Minor bugfixes and support JDK 14

.github/workflows/maven.yml, api/src/main/java/org/jboss/forge/roaster/model/JavaRecord.java, api/src/main/java/org/jboss/forge/roaster/model/JavaType.java, api/src/main/java/org/jboss/forge/roaster/model/source/JavaRecordSource.java, impl/src/main/java/org/jboss/forge/roaster/model/ast/TypeDeclarationFinderVisitor.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/EnumConstantBodyImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaRecordImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaSourceImpl.java, impl/src/main/java/org/jboss/forge/roaster/model/util/JDTOptions.java, impl/src/main/java/org/jboss/forge/roaster/spi/JavaParserImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/JavaRecordTest.java
There is a bug in Eclipse JDT (https://github.com/eclipse/eclipse.jdt.core/pull/60) that impacts when preview features are enabled
=> Support Record types

api/src/main/java/org/jboss/forge/roaster/model/JavaRecord.java, api/src/main/java/org/jboss/forge/roaster/model/source/JavaRecordSource.java, impl/src/main/java/org/jboss/forge/roaster/model/impl/JavaRecordImpl.java, tests/src/test/java/org/jboss/forge/test/roaster/model/JavaRecordTest.java
=> Support nested types in Records

tests/src/test/resources/org/jboss/forge/grammar/java/BigInterface.java
=> Update BigInterface.java license header

pom.xml
To make sure it builds with JDK 11
=> Set `maven.compiler.release` to 11

impl/pom.xml, pom.xml
- Update parent project version to ensure compatibility with latest dependencies.
- Clean up build configuration by removing obsolete properties.
=> Upgrade project dependencies and configurations

impl/pom.xml
- Configure Maven Shade Plugin to include resources in the manifest.
=> Generate `META-INF/MANIFEST.MF` in the roaster-jdt JAR
